### ISSUE TITLE
Support suite/test names

### ISSUE THREAD

**Issue by roblourens** [spoonscen/es6-mocha-snippets-vs-code#1]
Would be awesome to have snippets for the tdd syntax as well! (suite, test, setup, teardown, etc)

**Comment by spoonscen** [comment]
Ah! https://mochajs.org/#tdd
@roblourens I have never used these! You learn something new every day! Looks like a great addition to the snippets! Do you want to put a PR up for it?

**Comment by spoonscen** [comment]
@roblourens All set friend!

**Comment by roblourens** [comment]
Awesome, thanks. Sorry I meant to start on a PR :)
