### ISSUE TITLE
adding file scope (or glob pattern)

### ISSUE THREAD

**Issue by rokoroku** [spoonscen/es6-mocha-snippets-vs-code#11]
Currently, the mocha snippet is enabled for every js (or ts) files globally.

However, it would be better when it is activated only in specified file scopes. (e.g. `**/*.test.js`)

**Comment by spoonscen** [comment]
Thats a good call! Want to throw up a PR? This should be a configurable param.

**Comment by spoonscen** [comment]
@rokoroku Fixed in #16
