### ISSUE TITLE
Make semicolons optional

### ISSUE THREAD

**Issue by demisx** [spoonscen/es6-mocha-snippets-vs-code#12]
Is there anyway to instruct this extension not to insert semicolons in TypeScript? We don't use them and deleting semicolons each time a mocha snippet is unwrapped is PITA.

**Comment by spoonscen** [comment]
Yes I totally agree. I also don't use them. I am guilty of modifying the local extension code as a work around to actually solving this problem. I would definitely accept a PR on this!

**Comment by spoonscen** [comment]
@demisx Fixed in #16
