### ISSUE TITLE
"mocha-snippets.semicolons"

### ISSUE THREAD

**Issue by mattans13** [spoonscen/es6-mocha-snippets-vs-code#17]
Hi,

Thanks for the great extension!

in the documentation you suggest to use `"mocha-snippets.semicolons": boolean` which results in `Unknown configuration setting` error in VSCode. However if you use `"mocha-snippets.semicolon": boolean` (without the 's' in the end) then all is good. is it possible to fix the documentation?

**Comment by spoonscen** [comment]
Thanks for pointing that out! All set!
