### ISSUE TITLE
Don't ship .vscode-test

### ISSUE THREAD

**Issue by roblourens** [spoonscen/es6-mocha-snippets-vs-code#22]
Looking at extension sizes, I see that this extension ships all of vscode inside the .vscode-test folder. You should use a .vscodeignore file to omit that directory.

![image](https://user-images.githubusercontent.com/323878/39659179-ca87aac4-4fd7-11e8-8b48-9d292b3b4cb1.png)

**Comment by spoonscen** [comment]
Whoops! Thanks @roblourens :) Ill get that patched up :)

**Comment by darrinholst** [comment]
I'm still seeing this with 0.1.3

![3d184b3c-136f-4874-89de-63c58a074215](https://user-images.githubusercontent.com/4854/43199537-efb18ea6-8fd7-11e8-90e8-bfbc76c7d313.png)

**Comment by spoonscen** [comment]
@darrinholst Thanks so much. I'll take a look at it!
