### ISSUE TITLE
afterEach with fn snippet leaves the f in place

### ISSUE THREAD

**Issue by leonormes** [spoonscen/es6-mocha-snippets-vs-code#29]
When I type. `fafter <tab>` to get the `afterEach` block with function the f is still there after expanding the snippet
`fafterEach(function() {})`

**Comment by spoonscen** [comment]
Hey @leonormes thanks for the issues! Always happy to expand this extension.

I took a quick look at the snippet to see if it was a typo, https://github.com/spoonscen/es6-mocha-snippets-vs-code/blob/master/src/snippets.ts#L118

Unfortunately it is not a typo and some further debugging will have to happen here. Feel free to debug this and submit a PR when you find the solution! I can also take a look next time I have some free time.

Thanks!

**Comment by leonormes** [comment]
It was further down
[faftereach](https://github.com/spoonscen/es6-mocha-snippets-vs-code/blob/063df828f16cf84d8c6a0d23dd442e3eefc8bed9/src/snippets.ts#L168)

**Comment by spoonscen** [comment]
@leonormes Deployed! You will see this change in Version`0.2.2`
