### ISSUE TITLE
Mocha discourages use of arrow functions

### ISSUE THREAD

**Issue by prometheas** [spoonscen/es6-mocha-snippets-vs-code#3]
I think it's important to allow non-arrow callbacks to be used for the snippet expansions… and to make this the _default_ expansion style, as Mocha itself [discourages their use](http://mochajs.org/#arrow-functions):

> Passing arrow functions (“lambdas”) to Mocha is discouraged. Due to the lexical binding of `this`, such functions are unable to access the Mocha context.

**Comment by spoonscen** [comment]
Hey, @prometheas 
Thanks for your feedback. Mocha does discourage their use but also leaves this comment below.

> If you do not need to use Mocha’s context, lambdas should work. However, the result will be more difficult to refactor if the need eventually arises.

I have never needed the context in the tests I write, however, if you want to update your local installation to remove the arrow functions you can!

From [Visual Studio Code's website](https://code.visualstudio.com/docs/editor/extension-gallery) 
> Q: Where are extensions installed? 
A: Extensions are installed in your extensions folders. Depending on your platform, the global location is in the following folders:
> - Windows %USERPROFILE%\.vscode\extensions
> - Mac ~/.vscode/extensions
> - Linux ~/.vscode/extensions

**Comment by prometheas** [comment]
Oh, yea. I actually made my own snippets package to solve the matter 😁
