### ISSUE TITLE
Option to include types in typescript snippet

### ISSUE THREAD

**Issue by leonormes** [spoonscen/es6-mocha-snippets-vs-code#30]
I am using typescript and when I expand a snippet my linter complains that the functions in it do not have a type. They just need to be `it('should have type', function(): void {})`
How can I change this?

**Comment by spoonscen** [comment]
Hey @leonormes!

Thanks for the feedback! This is a great new feature for this extension. We would need to add language detection to the extension. Once we know a file is typescript or typescriptreact we could write a helper function similar to the one I linked [here](https://github.com/spoonscen/es6-mocha-snippets-vs-code/blob/master/src/extension.ts#L27), that would replace `function() {}` with  `function(): void {}` and `() =>` with `(): void =>`.  

Are you able to try implementing this? I would happy to review a PR.

Thanks,
Cory
