### ISSUE TITLE
Consider changing snippet prefixes

### ISSUE THREAD

**Issue by prometheas** [spoonscen/es6-mocha-snippets-vs-code#4]
In my experience, many of the prefixes this package is using become problematic when you're editing a non-empty Mocha file, due to the way VS Code seems to prefer matching existing symbols in its current files over matching snippet prefixes.

For example, open (or quickly create) a mocha test script with at least one `it` block, and then attempt to use the `it()` snippet in this package: you'll note that if you simply type `it` and then hit `TAB` or `ENTER`, the editor will fail to place the snippet. I am able to force it by resorting to tapping the arrow keys (in my configuration, I can hit the down arrow once and I'm in business), but this undermines the whole point of using snippets.

One way to address this is by using prefixes which do not collide with any of their expanded snippet text (for example, replacing `it` with `mit`, for `Mocha::it()`.

**Comment by spoonscen** [comment]
Hey,  @prometheas 

I have also noticed this as a pain point! I am unsure what to do here as the extension already has many many users. My best thinking says we could double the number of snippets and create additional aliases for them. If you want to submit a PR that does that I will gladly review it and get it live on the marketplace.

Thanks for taking the time to write this up!

**Comment by prometheas** [comment]
As mentioned on #3, I've created my own snippets package. It's presently in beta, so not yet available in the VS store; I just thought I'd offer the feedback, as nobody else seems to have reported it.

For what it's worth, if you'd use `m-it`, VS Code's fuzzy matching would be "backwards compatible" with your present release.

Stil, I would actually posit that backwards compatibility is worth breaking in this case, as it is itself the root of the conflict.

**Comment by spoonscen** [comment]
@prometheas  Want to take a peep at #5 I'll get it popped into the store if this makes the change you want!

**Comment by spoonscen** [comment]
@prometheas Sorry for the LONG delay. I have a PR up now that fixes all of the remaining issues.
This is Fixed #16 allowing you to put a custom prefix for the the snippets
