### ISSUE TITLE
it functions should have 'done' parameter

### ISSUE THREAD

**Issue by btmurrell** [spoonscen/es6-mocha-snippets-vs-code#7]
for successful tests, you must pass and call `done` handler in each `it` block.  why not create `it`, passing `done` to handler?

```javascript
it('', (done) => {
});
```

**Comment by spoonscen** [comment]
@btmurrell the `done` callback is used for async tests. Personally I use `Promise`s

```javascript
it('does the thing', () => {
  return somePromisedFunction().then((result) => {
    expect(result.foo).to.equal('bar')
    expect(result.quz).to.equal('qux')
  })
})
```

**Comment by spoonscen** [comment]
More recently using async/await still don't see much use for adding `done`. If there are more people that want it, we can consider putting in an additional snippets.
```ts
it('does the thing', async () => {
  const result = await somePromisedFunction()
  expect(result.foo).to.equal('bar')
  expect(result.quz).to.equal('qux')
})
```
