### ISSUE TITLE
Adding "context()" snippet

### ISSUE THREAD

**Issue by DavidBabel** [spoonscen/es6-mocha-snippets-vs-code#8]
Refering to official documentation, "context is an alias of describe" : 
https://mochajs.org/#bdd

I found it usefull, should be great to add it to this plugin

**Comment by spoonscen** [comment]
Go ahead and submit a PR!

**Comment by DavidBabel** [comment]
https://github.com/spoonscen/es6-mocha-snippets-vs-code/pull/9

**Comment by spoonscen** [comment]
Fixed with #9

**Comment by DavidBabel** [comment]
thx
